### ISSUE TITLE
What happened to spacemac dark theme when upgrade to vscode 1.16.0

### ISSUE THREAD

**Issue by soimy** [cometeer/spacemacs-vscode#2]
![screenshot-spacemac](https://user-images.githubusercontent.com/1550237/30255204-4e643fdc-96d4-11e7-9cf4-9a7258590c1a.jpg)

**Comment by SilentGodot** [comment]
I noticed this too. It seems that any color that is not specified defaults to #ff0000 now, which is red.
The dark theme leaves a lot of colors as empty strings (""), so a lot of things are red.

You can go to your extension directory and fix this yourself until they patch it.

I'll attach my fix here. (Note that the file extension should be .json)
[Spacemacs-dark-color-theme.txt](https://github.com/cometeer/spacemacs-vscode/files/1291543/Spacemacs-dark-color-theme.txt)

**Comment by cometeer** [comment]
Fixed now, thanks @SilentGodot 
Didn't realise this got popular and don't use GitHub on my new job unfortunately...
